# -*- coding: utf-8 -*-
"""DataAnalysis_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ego2xWs1cGf-lr31_OQSRVBSsAIPXFJ2
"""

import pandas

"""# Student Social Media Addiction Data Analysis"""

url='https://raw.githubusercontent.com/Mithilesh-23/Pytthon-Course/refs/heads/main/Students%20Social%20Media%20Addiction.csv?token=GHSAT0AAAAAADFH4O6XFF2WEJATJSOG7FLI2CSTOIQ'
df=pandas.read_csv(url)
print(df)

gender=df['Gender'].value_counts()
print(gender)

platform=df['Most_Used_Platform'].value_counts().head(3)
print(platform)

print(f"Most Dangerous platform nowdays of Addiction according to data : '{platform.index[0]}'")

avgUse=df[['Avg_Daily_Usage_Hours', 'Sleep_Hours_Per_Night']].mean()
print(avgUse)

print(f"Average use of mobile : {avgUse['Avg_Daily_Usage_Hours']:.2f} hr and sleep :{avgUse['Sleep_Hours_Per_Night']:.2f} hr")

edu = df[['Country', 'Academic_Level']].sort_values('Academic_Level').head(10)
print(edu)

affected=df['Affects_Academic_Performance'].value_counts()
print(affected)

meanAddictedScore=df['Addicted_Score'].mean()
print(f"Average Addicted Score of Student : {meanAddictedScore:.2f} %")

"""Country Wise Most Platform Use and Relationship Status

"""

countrynm=input("Enter the country name : ")
country=df[df['Country']==countrynm]
platform=country['Most_Used_Platform'].value_counts().head(1)
relation=country['Relationship_Status'].value_counts().head(1)

print(f"Most use platform in {countrynm} is {platform} and Relation ship Status is {relation}")

"""Sorting of Students by using Addicted_Score Country Wise

"""

countrynm=input("Enter the country name : ")
addictCount=df[df['Country']==countrynm]
print(addictCount[['Student_ID', 'Age', 'Gender', 'Affects_Academic_Performance', 'Addicted_Score']].sort_values('Addicted_Score', ascending=False))

df.rename(columns={'Avg_Daily_Usage_Hours':'Daily_Use', 'Affects_Academic_Performance':'Affect_Study', 'Sleep_Hours_Per_Night':'Sleep_hr'})

print("Age Wise Addicted Score")
ageAdt=df['Age'].value_counts()
ageAdt = ageAdt.rename("Addicted Score")
print(ageAdt)